### ISSUE TITLE
How can I publish IMU at 200 Hz?

### ISSUE THREAD

**Issue by arjunskumar** [ros-drivers/advanced_navigation_driver#13]

**Comment by nznobody** [comment]
Note: This repository is abandoned by Advanced Navigation Support <support@advancednavigation.com>. When asking them about this, they pointed me to:
- https://github.com/advanced-navigation/ros1-driver
- https://github.com/advanced-navigation/ros2-driver

**Comment by arjunskumar** [comment]
Thanks @nznobody
