### ISSUE TITLE
Yaw seems to be North-zero.

### ISSUE THREAD

**Issue by kylerlaird** [ros-drivers/advanced_navigation_driver#3]
My Spatial Dual works great with the Java interface; position and orientation are rock-solid.  However, when I use the ROS driver, I get an orientation that seems to be mis-referenced.  With my Spatial pointed (roughly) East, I get this from the Imu message:

orientation:
  x: -0.010506070219
  y: -0.012533034198
  z: 0.665283083916
  w: 0.746412038803

However, given that quaternion, I get 83 degrees.

In [1]: x = -0.010506070219
   ...: y = -0.012533034198
   ...: z = 0.665283083916
   ...: w = 0.746412038803
   ...:
   ...: import tf.transformations
   ...: import math
   ...:
   ...: print(map(math.degrees, tf.transformations.euler_from_quaternion([x, y, z, w])))
   ...:
[-1.8544214172334526, -0.27104406900104283, 83.42613987606788]

That would normally make sense to me, except that East should be 0 degrees in ROS.

http://www.ros.org/reps/rep-0103.html
"By the right hand rule, the yaw component of orientation increases as the child frame rotates counter-clockwise, and for geographic poses, yaw is zero when pointing east."

**Comment by an-scott** [comment]
Spatial Dual always outputs data with North equal to zero degrees.  You will need to do a translation within your software if necessary.

**Comment by mikepurvis** [comment]
Per REP 103, ROS messages use the east-north-up convention: http://www.ros.org/reps/rep-0103.html#coordinate-frame-conventions

To maximize compatibility between components, the native data from the device should ideally be translated in the driver to the ROS convention before being published. However, obviously it's up to individual maintainers to decide what they want to do.

**Comment by kylerlaird** [comment]
https://github.com/kylerlaird/advanced_navigation_driver
